### ISSUE TITLE
add a search button to the navigation next to the search bar

### ISSUE THREAD

**Issue by sharicarlson13** [SFDO-Community-Sprints/sprintys-community-resources#4]

**Comment by JodiNA** [comment]
Feedback from London sprint is that it's confusing that there is a "curator login" button next to the search bar. Users can click that button thinking they are clicking a "search" button when really they will navigate to a login page. Investigate how to make this clearer - either add a search button, change order of nav so there's space between search bar and button, etc.

**Comment by JodiNA** [comment]
Changed settings for the search bar on home page and non-home page navs to include the search button. Magnifying glass color isn't customizable.
![image](https://user-images.githubusercontent.com/8515331/214749605-e5cb11ce-f007-4676-8fdc-82ed4370af1b.png)
