### ISSUE TITLE
Review/update Dashboard to monitor submissions

### ISSUE THREAD

**Issue by shiratamara** [SFDO-Community-Sprints/sprintys-community-resources#42]
same dashboard as reviewing curation https://github.com/orgs/SFDO-Community-Sprints/projects/11/views/1?filterQuery=phase%3A%22Phase+1%22&pane=issue&itemId=66440326

**Comment by DatabaseDeanne** [comment]
First draft of the updated dashboard can be found [here](https://sprintyscommunityresources.lightning.force.com/lightning/r/Dashboard/01Z4w000000xmbGEAQ/view?queryScope=userFolders).

**Comment by JodiNA** [comment]
- Update audit dashboard to correct auditing cadence. Currently set to 1x/year.
- Add additional chart that shows approval by date (either by month or cumulative).

Maybe in future add breakdown by topic or descriptive fields - incorporate chart from Sprinty's community resource dashboard.

**Comment by DatabaseDeanne** [comment]
JK added [Approved Submissions by Review Date](https://sprintyscommunityresources.lightning.force.com/lightning/r/Dashboard/01Z4w000000xmbGEAQ/view?queryScope=userFolders) to the dashboard.


**Suggestions shared during SCR call:** 

- Keep the initial screen of type of resource - Maybe add some new categories.
- Remove the categorization metadata fields - Let the curators do the categorization
- Change the resource questions to guide the submitter to share more information about the resource and how it used. Curators will use responses to create the Resource Title and Description
- Consider making the resource questions more contextual/customized to type of resource selected in the first screen.

**Next Steps:**
- JK will update the mockup and share on Slack for feedback on revised format and questions. Revisit at next meeting.
- Build a new screen flow for testing with users.

**Comment by DatabaseDeanne** [comment]
> First draft of the updated dashboard can be found [here](https://sprintyscommunityresources.lightning.force.com/lightning/r/Dashboard/01Z4w000000xmbGEAQ/view?queryScope=userFolders).

The most recent update changed the audit cadence to every 90 days.

**Comment by shiratamara** [comment]
We reviewed at the meeting and are marking it as done! Thanks Deanne! 
We will use it to review new submissions at the beginning of our biweekly meetings.
