### ISSUE TITLE
Finalize user experience survey

### ISSUE THREAD

**Issue by shiratamara** [SFDO-Community-Sprints/sprintys-community-resources#45]
Also make a plan for people to take it (already have draft)

**Comment by johnckin** [comment]
@taniadoa  Here is the link to the draft of the Sprinty Usability Survey that I worked on. Let me know if you have any questions.
https://docs.google.com/document/d/1hb6i0_fcqEcFDma9BR5RSl2iGQ2nHuJtku1t-ZlUpV0/edit?usp=sharing

**Comment by taniadoa** [comment]
Reviewed the draft already in place. It’s a good survey. However, unclear who we will send this to and how. Questions for the team: (2) Do we want to try posting to the community see if we get any bites? (2) I like the questions but is it too long for your average survey taker?

**Comment by taniadoa** [comment]
This was finalized in time for the September 2024 Sprint https://forms.gle/b6VawqZ3gk7Z3hok6
